# Generated by Django 4.2.19 on 2025-05-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('horario', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
