# Generated by Django 4.2.19 on 2025-05-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresoejercicio',
            name='series',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
