# Generated by Django 4.2.19 on 2025-05-21 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrenamientos', '0002_progresoejercicio_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.PositiveIntegerField()),
                ('peso_levantado', models.FloatField()),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.entrenamiento')),
            ],
        ),
        migrations.RemoveField(
            model_name='progresopeso',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ProgresoEjercicio',
        ),
        migrations.DeleteModel(
            name='ProgresoPeso',
        ),
    ]
